/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasiujian;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Kategori extends javax.swing.JFrame {

    private int userId;
    private String username;
    private String role;
    
    /**
     * Default constructor (Kept for NetBeans GUI Builder compatibility)
     */
    public Kategori() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }
    
    public Kategori(int userId, String username, String role) {
        initComponents();
        this.userId = userId;
        this.username = username;
        this.role = role;
        System.out.println(userId + " " + username + " " + role);
        checkCompletedCategories();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * Queries the database to see which categories the user has already completed.
     * Disables and grays out the corresponding buttons.
     */
    private void checkCompletedCategories() {
        Connection conn = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        
        try {
            conn = DatabaseConnection1.getConnection();
            
            // Query to fetch all category IDs this user has already taken
            String sql = "SELECT category_id FROM exam_results WHERE user_id = ?";
            pst = conn.prepareStatement(sql);
            pst.setInt(1, this.userId);
            
            rs = pst.executeQuery();
            
            // Loop through the results and disable corresponding buttons
            while (rs.next()) {
                int catId = rs.getInt("category_id");
                
                switch (catId) {
                    case 1: // Addition
                        btnAdd.setEnabled(false);
                        btnAdd.setBackground(Color.DARK_GRAY);
                        break;
                    case 2: // Subtraction
                        btnMin.setEnabled(false);
                        btnMin.setBackground(Color.DARK_GRAY);
                        break;
                    case 3: // Multiplication
                        btnTme.setEnabled(false);
                        btnTme.setBackground(Color.DARK_GRAY);
                        break;
                    case 4: // Division
                        btnDiv.setEnabled(false);
                        btnDiv.setBackground(Color.DARK_GRAY);
                        break;
                }
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Failed to load category status:\n" + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (rs != null) rs.close();
                if (pst != null) pst.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblJdl = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnMin = new javax.swing.JButton();
        btnTme = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuUji = new javax.swing.JMenu();
        mnuNil = new javax.swing.JMenu();
        mnuLot = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 255, 204));
        jPanel2.setForeground(new java.awt.Color(0, 204, 204));

        lblJdl.setBackground(new java.awt.Color(0, 0, 0));
        lblJdl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblJdl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJdl.setText("KATEGORI UJIAN");

        btnAdd.setBackground(new java.awt.Color(204, 0, 0));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("+");
        btnAdd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnMin.setBackground(new java.awt.Color(0, 0, 153));
        btnMin.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnMin.setForeground(new java.awt.Color(255, 255, 255));
        btnMin.setText("-");
        btnMin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinActionPerformed(evt);
            }
        });

        btnTme.setBackground(new java.awt.Color(0, 153, 0));
        btnTme.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnTme.setForeground(new java.awt.Color(255, 255, 255));
        btnTme.setText("x");
        btnTme.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTmeActionPerformed(evt);
            }
        });

        btnDiv.setBackground(new java.awt.Color(153, 0, 153));
        btnDiv.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnDiv.setForeground(new java.awt.Color(255, 255, 255));
        btnDiv.setText(":");
        btnDiv.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnTme, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMin, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJdl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJdl)
                .addGap(104, 104, 104)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMin, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTme, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        mnuUji.setText("Ujian");
        mnuUji.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuUjiMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuUji);

        mnuNil.setText("Nilai");
        mnuNil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuNilMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuNil);

        mnuLot.setText("Logout");
        mnuLot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuLotMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuLot);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        Ujian examForm = new Ujian(1, "Penjumlahan", userId, username, role);
        examForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinActionPerformed
        Ujian examForm = new Ujian(2, "Pengurangan", userId, username, role);
        examForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMinActionPerformed

    private void btnTmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTmeActionPerformed
        Ujian examForm = new Ujian(3, "Perkalian", userId, username, role);
        examForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTmeActionPerformed

    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivActionPerformed
        Ujian examForm = new Ujian(4, "Pembagian", userId, username, role);
        examForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDivActionPerformed

    private void mnuUjiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuUjiMouseClicked
        Kategori kategoriForm = new Kategori(userId, username, role);
        kategoriForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnuUjiMouseClicked

    private void mnuNilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuNilMouseClicked
        Nilai nilai = new Nilai(userId, username, role);
        nilai.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnuNilMouseClicked

    private void mnuLotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuLotMouseClicked
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnuLotMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kategori().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnMin;
    private javax.swing.JButton btnTme;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblJdl;
    private javax.swing.JMenu mnuLot;
    private javax.swing.JMenu mnuNil;
    private javax.swing.JMenu mnuUji;
    // End of variables declaration//GEN-END:variables
}
